version: "3"

services:
  server:
    container_name: grpc-server
    image: grpc-server
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    networks:
      - grpc

  client:
    container_name: grpc-client
    image: grpc-client
    restart: unless-stopped
    environment:
      TZ: Europe/Berlin
    networks:
      - grpc

networks:
  grpc:
    external: true
